### ISSUE TITLE
Working with Raspberry Pi?

### ISSUE THREAD

**Issue by 1Dimension1** [dmytro-tsepilov/pq_bms_bluetooth#3]
Hi,

I really like the project and would love to run it. I tried running it on a Pi4 with raspbian and got connection errors from the bluetooth library on both python 3.9 as with 3.11. I did manage to scan bluetooth and find the MAC of the battery and used the commands described in the Readme.

How did you manage to run it, using a laptop or?
Did somebody successfully got it working on a Pi?

Hardware:
- PowerQueen 25.6V 100Ah
- Pi4 with Raspbian (Bullseye i think)

I will post errors logs later because i turned it off.

-------------------------
Edit:

Oops found in readme on bottom:

Software:
    Python 3.10, 3.11
    Linux Ubuntu 22.04
    **Raspberry Pi OS Debian 12 (bookworm) (kernel 6.6+)**

Maybe i should try with bookworm then on a Pi4

**Comment by dmytro-tsepilov** [comment]
Hi,
I personally use and develop it on Raspberry Pi 5 (Debian 12 (bookworm) (kernel 6.6.51-1+rpt3)
Python 3.11.2.

Also tested on Ubuntu 22.04 (kernel 5.15.0-125-generic #135-Ubuntu)
Python 3.11
CPU: Intel Pentium Gold G6400
Motherboard: Asus PRIME H510M-A WIFI

**UPD:** 
Tested on Laptop with Ubuntu 22.04.5 (kernel 6.8.0-48-generic #48)
Python 3.10.12
Bluetooth module: Intel Corp. AX201 Bluetooth

---
Can you please try run the bms python script with following flag?
` python3 main.py AA:BB:CC... --services`

And post output here?

**Comment by 1Dimension1** [comment]
Thanks for your fast response :)
I just reinstalled latest PiOS lite on the Pi4 and will let you know

`Linux raspberrypi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64`

**Comment by 1Dimension1** [comment]
--services does crash but --bms is working now. `bleutoothctl scan` on showed this time also manufacturer data


```
Traceback (most recent call last):
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 273, in connect
    await self.get_services(
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 661, in get_services
    self.services = await manager.get_services(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 666, in get_services
    await self._wait_for_services_discovery(device_path)
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 783, in _wait_for_services_discovery
    done, _ = await asyncio.wait(
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 525, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pq_bms_bluetooth/main.py", line 47, in <module>
    main()
  File "/opt/pq_bms_bluetooth/main.py", line 38, in main
    asyncio.run(request.print_services())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/pq_bms_bluetooth/request.py", line 58, in print_services
    async with BleakClient(self.bluetooth_device_mac, timeout=self.bluetooth_timeout) as client:
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/__init__.py", line 570, in __aenter__
    await self.connect()
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pq_bms_bluetooth/venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 151, in connect
    async with async_timeout(timeout):
  File "/usr/lib/python3.11/asyncio/timeouts.py", line 98, in __aexit__
    raise TimeoutError
TimeoutError
```



with --bms

```
{
    "packVoltage": 26044,
    "voltage": 26362,
    "batteryPack": {
        "1": 3.295,
        "2": 3.295,
        "3": 3.295,
        "4": 3.295,
        "5": 3.295,
        "6": 3.296,
        "7": 3.296,
        "8": 3.295
    },
    
    And the rest
```

**Comment by 1Dimension1** [comment]
--bms often fails the same way with a timeout when running but at least there is some communication

**Comment by 1Dimension1** [comment]
After multiple tries i got output from --services

```
f000ffc0-0451-4000-b000-000000000000 (Handle: 46): Unknown
        characteristic: $f000ffc1-0451-4000-b000-000000000000 (Handle: 47): Unknown
        Error: [org.bluez.Error.NotPermitted] Read not permitted
        characteristic: $f000ffc2-0451-4000-b000-000000000000 (Handle: 51): Unknown
        Error: [org.bluez.Error.NotPermitted] Read not permitted
00001801-0000-1000-8000-00805f9b34fb (Handle: 10): Generic Attribute Profile
        characteristic: $00002a05-0000-1000-8000-00805f9b34fb (Handle: 11): Service Changed
        bytearray(b'\x01\x00\xff\xff')
00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
        characteristic: $00002a01-0000-1000-8000-00805f9b34fb (Handle: 4): Appearance
        bytearray(b'\x00\x00')
        characteristic: $00002a00-0000-1000-8000-00805f9b34fb (Handle: 2): Device Name
        bytearray(b'')
        characteristic: $00002a02-0000-1000-8000-00805f9b34fb (Handle: 6): Peripheral Privacy Flag
        bytearray(b'\x00')
        characteristic: $00002a04-0000-1000-8000-00805f9b34fb (Handle: 8): Peripheral Preferred Connection Parameters
        bytearray(b'\x0c\x00\x10\x00\x00\x00X\x02')
0000180a-0000-1000-8000-00805f9b34fb (Handle: 23): Device Information
        characteristic: $00002a26-0000-1000-8000-00805f9b34fb (Handle: 32): Firmware Revision String
        bytearray(b'6.1.2')
        characteristic: $00002a24-0000-1000-8000-00805f9b34fb (Handle: 26): Model Number String
        bytearray(b'BK-BLE-1.0')
        characteristic: $00002a23-0000-1000-8000-00805f9b34fb (Handle: 36): System ID
        bytearray(b'\x124V\xff\xfe\x9a\xbc\xde')
        characteristic: $00002a27-0000-1000-8000-00805f9b34fb (Handle: 30): Hardware Revision String
        bytearray(b'1.0.0')
        characteristic: $00002a25-0000-1000-8000-00805f9b34fb (Handle: 28): Serial Number String
        bytearray(b'1.0.0.0-LE')
        characteristic: $00002a2a-0000-1000-8000-00805f9b34fb (Handle: 38): IEEE 11073-20601 Regulatory Cert. Data List
        bytearray(b'\xff\xee\xdd\xcc\xbb\xaa')
        characteristic: $00002a50-0000-1000-8000-00805f9b34fb (Handle: 40): PnP ID
        bytearray(b'\x02^\x04@\x00\x00\x03')
        characteristic: $00002a28-0000-1000-8000-00805f9b34fb (Handle: 34): Software Revision String
        bytearray(b'6.3.0')
        characteristic: $00002a29-0000-1000-8000-00805f9b34fb (Handle: 24): Manufacturer Name String
        bytearray(b'BEKEN SAS')
0000ffe0-0000-1000-8000-00805f9b34fb (Handle: 14): Vendor specific
        characteristic: $0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 15): Vendor specific
        Error: [org.bluez.Error.NotPermitted] Read not permitted
        characteristic: $0000ffe2-0000-1000-8000-00805f9b34fb (Handle: 18): Vendor specific
        Error: [org.bluez.Error.NotPermitted] Read not permitted
        characteristic: $0000ffe3-0000-1000-8000-00805f9b34fb (Handle: 20): Vendor specific
        Error: [org.bluez.Error.NotPermitted] Read not permitted
0000180f-0000-1000-8000-00805f9b34fb (Handle: 42): Battery Service
        characteristic: $00002a19-0000-1000-8000-00805f9b34fb (Handle: 43): Battery Level
        bytearray(b'\x00')
2024-11-12 21:23:52,827 [print_services] Disconnecting xxx
2024-11-12 21:23:52,828 [print_services] Disconnected xxx
```

**Comment by dmytro-tsepilov** [comment]
So it looks like main issue is timeout, or too long response from device

**Comment by 1Dimension1** [comment]
I can try increasing timeout from 2 to 4 for example

https://github.com/1Dimension1/pq_bms_bluetooth/blob/272c6dcc211790ff8b8a85c7378bbdb286b76edc/request.py#L12C8-L13C1

**Comment by dmytro-tsepilov** [comment]
> I can try increasing timeout from 2 to 4 for example

Yes, please try.
And how far your battery from your device?

It could be issue due to overloaded 2.4Ghz frequency with other devices

**Comment by 1Dimension1** [comment]
It's in the garage next to it. 

With timeout = 4 i get consistent good output

**Comment by dmytro-tsepilov** [comment]
> It's in the garage next to it.
> 
> With timeout = 4 i get consistent good output

Seems I need to add timeout value to command line parameters

**Comment by dmytro-tsepilov** [comment]
@1Dimension1 I added new version with `--timeout` parameter and default timeout 4 seconds
Hope it will helps
